version: '3.8'

services:
  laravel:
    build: ./docker/local/php
    volumes:
      - ./api:/var/www:cached
      - ./docker/local/php/php.ini:/usr/local/etc/php/php.ini
  nginx:
    image: nginx
    container_name: nginx-for-admin # 他のプロジェクトでnginxを使用していて競合してしまう
    ports:
      - 8880:80
    volumes:
      - ./docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
