name: Build Docker Image and Push to ECR

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -f docker/develop/php/Dockerfile .
